# Generated by Django 5.0.2 on 2025-05-04 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_department_alter_telegramuser_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('daily', 'Ежедневный'), ('weekly', 'Еженедельный'), ('monthly', 'Ежемесячный'), ('quarterly', 'Квартальный')], max_length=20, verbose_name='Тип отчета')),
                ('period_start', models.DateField(verbose_name='Начало периода')),
                ('period_end', models.DateField(verbose_name='Конец периода')),
                ('content', models.JSONField(verbose_name='Содержание отчета')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField(default=0, verbose_name='Уверенность')),
                ('keywords', models.JSONField(default=list, verbose_name='Ключевые слова')),
                ('analysis_result', models.JSONField(default=dict, verbose_name='Результат анализа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.complaint', verbose_name='Обращение')),
                ('suggested_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.department', verbose_name='Предложенное управление')),
            ],
            options={
                'verbose_name': 'Анализ ИИ',
                'verbose_name_plural': 'Анализы ИИ',
            },
        ),
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Время отправки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.complaint', verbose_name='Обращение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Email уведомление',
                'verbose_name_plural': 'Email уведомления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(verbose_name='Период')),
                ('total_complaints', models.IntegerField(default=0, verbose_name='Всего обращений')),
                ('completed_complaints', models.IntegerField(default=0, verbose_name='Выполнено обращений')),
                ('overdue_complaints', models.IntegerField(default=0, verbose_name='Просрочено обращений')),
                ('average_response_time', models.DurationField(blank=True, null=True, verbose_name='Среднее время ответа')),
                ('average_completion_time', models.DurationField(blank=True, null=True, verbose_name='Среднее время выполнения')),
                ('satisfaction_rate', models.FloatField(default=0, verbose_name='Удовлетворенность')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.department', verbose_name='Управление')),
            ],
            options={
                'verbose_name': 'KPI управления',
                'verbose_name_plural': 'KPI управлений',
                'unique_together': {('department', 'period')},
            },
        ),
    ]
