# Generated by Django 5.0.2 on 2025-05-05 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_report_aianalysis_emailnotification_departmentkpi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramOrder',
        ),
    ]
